FileVersion = 1
Dependencies = {corlib = "*", Strawberry = "*"}

[Project]
Name = "SampleGame"
TargetType = "BeefGUIApplication"
StartupObject = "Strawberry.Sample.Program"
DefaultNamespace = "Strawberry.Sample"

[[Project.DistinctOptions]]
Filter = ""
ReflectAlwaysInclude = "IncludeAll"

[[ProjectFolder.Items]]
Type = "Folder"
Name = "Physics"
AutoInclude = true
